direction: right

# --- 0. STYLES ---
style: {
  opacity: 0.0
  fill: transparent
}

# --- 1. SETTINGS ---
classes: {
  entity: {
    shape: rectangle
    style: {border-radius: 10; fill: "#FFFFFF"; stroke: "#333333"}
  }
  rel: {
    shape: diamond
    style: {fill: "#F2F2F7"; stroke: "#8E8E93"}
  }
  attr: {
    shape: oval
    # width: 100; height: 50
    style: {fill: "#F0F8FF"; stroke: "#4682B4"; stroke-dash: 3}
  }
}

# --- 2. ENTITIES ---
ADMINS: {class: entity; label: "ADMINS"}
DATPHONG: {class: entity; label: "DATPHONG"}
DICHVU: {class: entity; label: "DICHVU"}
LOAIPHONG: {class: entity; label: "LOAIPHONG"}
PAYMENTS: {class: entity; label: "PAYMENTS"}
PERMISSIONS: {class: entity; label: "PERMISSIONS"}
PHONG: {class: entity; label: "PHONG"}
REFUNDS: {class: entity; label: "REFUNDS"}
REVIEWS: {class: entity; label: "REVIEWS"}
ROLES: {class: entity; label: "ROLES"}
USERS: {class: entity; label: "USERS"}
VOUCHERS: {class: entity; label: "VOUCHERS"}

# --- 3. RELATIONSHIPS ---
# ngôn ngữ "tự nhiên"

# ADMINS -> REFUNDS: duyệt
admins_refunds: {class: rel; label: "duyệt"}
ADMINS -- admins_refunds: (1, n)
admins_refunds -- REFUNDS: (1, n)

# ADMINS -> ROLES: được cấp
# n - n: viền cam
admins_roles: {class: rel; label: "được cấp"; style: {stroke: orange}}
ADMINS -- admins_roles: (n, n)
admins_roles -- ROLES: (n, n)

DATPHONG -> DICHVU: bao gồm
DATPHONG -> PAYMENTS: được
DATPHONG -> PHONG: có nhiều
DATPHONG -> REVIEWS: được
LOAIPHONG <- PHONG: thuộc

# PAYMENTS -> REFUNDS: được
payments_refunds: {class: rel; label: "được"}
PAYMENTS -- payments_refunds: (1, n)
payments_refunds -- REFUNDS: (1, n)

# ROLES -> PERMISSIONS: có các
roles_permissions: {class: rel; label: "có gán"; style: {stroke: orange}}
ROLES -- roles_permissions: (n, n)
roles_permissions -- PERMISSIONS: (n, n)

# USERS -> DATPHONG: thực hiện
users_datphong: {class: rel; label: "thực hiện"}
USERS -- users_datphong: (1, n)
users_datphong -- DATPHONG: (1, n)

# USERS -> PAYMENTS: thực hiện
users_payment: {class: rel; label: "thực hiện"}
USERS -- users_payment: (1, n)
users_payment -- PAYMENTS: (1, n)

# USERS -> REFUNDS: yêu cầu
users_refunds: {class: rel; label: "yêu cầu"}
USERS -- users_refunds: (1, n)
users_refunds -- REFUNDS: (1, n)

# USERS -> REVIEWS: viết
users_reviews: {class: rel; label: "viết"}
USERS -- users_reviews: (1, n)
users_reviews -- REVIEWS: (1, n)

# VOUCHERS -> DATPHONG: áp dụng cho
vouchers_datphong: {class: rel; label: "áp dụng"}
VOUCHERS -- vouchers_datphong: (1, n)
vouchers_datphong -- DATPHONG: (1, n)
