# direction: right

# Tiêu đề: căn góc trên-giữa
# title: |md
#   # Mô Hình Thực Thể Quan Hệ (ER Diagram Chen Notation)
# | {near: top-center}

# title.style: {
# font-size: 20
# font: "mono"
# }

# --- 0. STYLES ---
style: {
  # font: "mono"
  opacity: 0.0
  # fill: "#dcdcdc"
  # stroke: "orange"
  # stroke-width: 5
}

# --- 1. CSS STYLES (THEME) ---
classes: {
  # Thực thể: Chữ nhật bo góc Apple style
  entity: {
    shape: rectangle
    style: {
      border-radius: 15
      stroke-width: 2
      fill: "#FFFFFF"
      stroke: "#333333"
    }
  }

  # Quan hệ (Relationship): Hình thoi
  rel: {
    shape: diamond
    style: {
      fill: "#F2F2F7"
      stroke: "#8E8E93"
      stroke-width: 2
    }
  }

  # Thuộc tính: Oval
  attr: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
    }
  }

  # Khóa chính: gạch chân
  # viền xanh
  attr_pri: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa chính là khóa khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_pri: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_key: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      # underline: true
    }
  }
}

# MARK: PAYMENTS
PAYMENTS: {class: entity; label: "PAYMENTS"}
payments_id: {class: attr_pri; label: "id"}
payments_booking_id: {class: attr_foreign_key; label: "booking_id"}
payments_user_id: {class: attr_foreign_key; label: "user_id"}
payments_so_tien: {class: attr; label: "so_tien"}
payments_phuong_thuc: {class: attr; label: "phuong_thuc"; width: 120}
payments_trang_thai: {class: attr; label: "trang_thai"}
payments_created_at: {class: attr; label: "created_at"; width: 110}

PAYMENTS -- payments_id: {style: {stroke-width: 1}}
PAYMENTS -- payments_booking_id: {style: {stroke-width: 1; stroke: orange}}
PAYMENTS -- payments_user_id: {style: {stroke-width: 1; stroke: orange}}
PAYMENTS -- payments_so_tien: {style: {stroke-width: 1}}
PAYMENTS -- payments_phuong_thuc: {style: {stroke-width: 1}}
PAYMENTS -- payments_trang_thai: {style: {stroke-width: 1}}
PAYMENTS -- payments_created_at: {style: {stroke-width: 1}}
