# direction: right

# Tiêu đề: căn góc trên-giữa
# title: |md
#   # Mô Hình Thực Thể Quan Hệ (ER Diagram Chen Notation)
# | {near: top-center}

# title.style: {
# font-size: 20
# font: "mono"
# }

# --- 0. STYLES ---
style: {
  # font: "mono"
  opacity: 0.0
  fill: transparent
  # stroke: "orange"
  # stroke-width: 5
}

# --- 1. CSS STYLES (THEME) ---
classes: {
  # Thực thể: Chữ nhật bo góc Apple style
  entity: {
    shape: rectangle
    style: {
      border-radius: 15
      stroke-width: 2
      fill: "#FFFFFF"
      stroke: "#333333"
    }
  }

  # Quan hệ (Relationship): Hình thoi
  rel: {
    shape: diamond
    style: {
      fill: "#F2F2F7"
      stroke: "#8E8E93"
      stroke-width: 2
    }
  }

  # Thuộc tính: Oval
  attr: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
    }
  }

  # Khóa chính: gạch chân
  # viền xanh
  attr_pri: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa chính là khóa khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_pri: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_key: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      # underline: true
    }
  }
}

# MARK: DATPHONG
DATPHONG: {class: entity; label: "DATPHONG"}
datphong_id: {class: attr_pri; label: "id"}
datphong_user_id: {class: attr; label: "user_id"}
datphong_voucher_id: {class: attr; label: "voucher_id"}
datphong_check_in: {class: attr; label: "check_in"}
datphong_check_out: {class: attr; label: "check_out"}
datphong_trang_thai: {class: attr; label: "trang_thai"}
datphong_created_at: {class: attr; label: "created_at"; width: 110}

DATPHONG -- datphong_id
DATPHONG -- datphong_user_id
DATPHONG -- datphong_voucher_id
DATPHONG -- datphong_check_in
DATPHONG -- datphong_check_out
DATPHONG -- datphong_trang_thai
DATPHONG -- datphong_created_at
