# direction: right

# Tiêu đề: căn góc trên-giữa
# title: |md
#   # Mô Hình Thực Thể Quan Hệ (ER Diagram Chen Notation)
# | {near: top-center}

# title.style: {
# font-size: 20
# font: "mono"
# }

# --- 0. STYLES ---
style: {
  # font: "mono"
  opacity: 0.0
  fill: transparent
  # stroke: "orange"
  # stroke-width: 5
}

# --- 1. CSS STYLES (THEME) ---
classes: {
  # Thực thể: Chữ nhật bo góc Apple style
  entity: {
    shape: rectangle
    style: {
      border-radius: 15
      stroke-width: 2
      fill: "#FFFFFF"
      stroke: "#333333"
    }
  }

  # Quan hệ (Relationship): Hình thoi
  rel: {
    shape: diamond
    style: {
      fill: "#F2F2F7"
      stroke: "#8E8E93"
      stroke-width: 2
    }
  }

  # Thuộc tính: Oval
  attr: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
    }
  }

  # Khóa chính: gạch chân
  # viền xanh
  attr_pri: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa chính là khóa khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_pri: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_key: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      # underline: true
    }
  }
}

# MARK: USERS
USERS: {class: entity; label: "USERS"}
users_id: {class: attr_pri; label: "id"}
users_email: {class: attr; label: "email"}
users_phone: {class: attr; label: "phone"}
users_password_hash: {class: attr; label: "password_hash"; width: 140}
users_full_name: {class: attr; label: "full_name"}
users_status: {class: attr; label: "status"}
users_created_at: {class: attr; label: "created_at"; width: 110}
users_updated_at: {class: attr; label: "updated_at"; width: 110}

USERS -- users_id: {style: {stroke-width: 1}}
USERS -- users_email: {style: {stroke-width: 1}}
USERS -- users_password_hash: {style: {stroke-width: 1}}
USERS -- users_full_name: {style: {stroke-width: 1}}
USERS -- users_phone: {style: {stroke-width: 1}}
USERS -- users_status: {style: {stroke-width: 1}}
USERS -- users_created_at: {style: {stroke-width: 1}}
USERS -- users_updated_at: {style: {stroke-width: 1}}
