# direction: right

# Tiêu đề: căn góc trên-giữa
# title: |md
#   # Mô Hình Thực Thể Quan Hệ (ER Diagram Chen Notation)
# | {near: top-center}

# title.style: {
# font-size: 20
# font: "mono"
# }

# --- 0. STYLES ---
style: {
  # font: "mono"
  opacity: 0.0
  fill: transparent
  # stroke: "orange"
  # stroke-width: 5
}

# --- 1. CSS STYLES (THEME) ---
classes: {
  # Thực thể: Chữ nhật bo góc Apple style
  entity: {
    shape: rectangle
    style: {
      border-radius: 15
      stroke-width: 2
      fill: "#FFFFFF"
      stroke: "#333333"
    }
  }

  # Quan hệ (Relationship): Hình thoi
  rel: {
    shape: diamond
    style: {
      fill: "#F2F2F7"
      stroke: "#8E8E93"
      stroke-width: 2
    }
  }

  # Thuộc tính: Oval
  attr: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
    }
  }

  # Khóa chính: gạch chân
  # viền xanh
  attr_pri: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa chính là khóa khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_pri: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_key: {
    shape: oval
    width: 90
    height: 40
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      # underline: true
    }
  }
}

# MARK: REVIEWS
REVIEWS: {class: entity; label: "REVIEWS"}
reviews_id: {class: attr_pri; label: "id"}
reviews_user_id: {class: attr_foreign_key; label: "user_id"; width: 120}
reviews_phong_id: {class: attr_foreign_key; label: "phong_id"; width: 120}
reviews_datphong_id: {class: attr_foreign_key; label: "datphong_id"; width: 120}
reviews_so_sao: {class: attr; label: "so_sao"}
reviews_binh_luan: {class: attr; label: "binh_luan"; width: 110}
reviews_ngay_danh_gia: {class: attr; label: "ngay_danh_gia"; width: 120}
reviews_trang_thai: {class: attr; label: "trang_thai"; width: 110}
reviews_created_at: {class: attr; label: "created_at"; width: 110}
reviews_updated_at: {class: attr; label: "updated_at"; width: 110}

REVIEWS -- reviews_id: {style: {stroke-width: 1}}
REVIEWS -- reviews_user_id: {style: {stroke-width: 1; stroke: orange}}
REVIEWS -- reviews_phong_id: {style: {stroke-width: 1; stroke: orange}}
REVIEWS -- reviews_datphong_id: {style: {stroke-width: 1; stroke: orange}}
REVIEWS -- reviews_so_sao: {style: {stroke-width: 1}}
REVIEWS -- reviews_binh_luan: {style: {stroke-width: 1}}
REVIEWS -- reviews_ngay_danh_gia: {style: {stroke-width: 1}}
REVIEWS -- reviews_trang_thai: {style: {stroke-width: 1}}
REVIEWS -- reviews_created_at: {style: {stroke-width: 1}}
REVIEWS -- reviews_updated_at: {style: {stroke-width: 1}}
