# direction: right

# Tiêu đề: căn góc trên-giữa
# title: |md
#   # Mô Hình Thực Thể Quan Hệ (ER Diagram Chen Notation)
# | {near: top-center}

# title.style: {
# font-size: 20
# font: "mono"
# }

# --- 0. STYLES ---
style: {
  # font: "mono"
  opacity: 0.0
  fill: transparent
  # stroke: "orange"
  # stroke-width: 5
}

# --- 1. CSS STYLES (THEME) ---
classes: {
  # Thực thể: Chữ nhật bo góc Apple style
  entity: {
    shape: rectangle
    style: {
      border-radius: 15
      stroke-width: 2
      fill: "#FFFFFF"
      stroke: "#333333"
    }
  }

  # Quan hệ (Relationship): Hình thoi
  rel: {
    shape: diamond
    style: {
      fill: "#F2F2F7"
      stroke: "#8E8E93"
      stroke-width: 2
    }
  }

  # Thuộc tính: Oval
  attr: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
    }
  }

  # Khóa chính: gạch chân
  # viền xanh
  attr_pri: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa chính là khóa khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_pri: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_key: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      # underline: true
    }
  }
}

# MARK: REFUNDS
REFUNDS: {class: entity; label: "REFUNDS"}

refunds_id: {class: attr_pri; label: "ID Hoàn Tiền"}
# refunds_payment_id: {class: attr_foreign_key; label: "payment_id"; width: 120}
refunds_so_tien_hoan: {class: attr; label: "Số Tiền Hoàn"}
refunds_trang_thai: {class: attr; label: "Trạng Thái"}
refunds_ly_do: {class: attr; label: "Lý Do"}
# refunds_requested_by: {class: attr_foreign_key; label: "requested_by"; width: 120}
# refunds_approved_by: {class: attr_foreign_key; label: "approved_by"; width: 120}
# refunds_created_at: {class: attr; label: "created_at"; width: 110}
# refunds_updated_at: {class: attr; label: "updated_at"; width: 110}

REFUNDS -- refunds_id
# REFUNDS -- refunds_payment_id: {style: {stroke-width: 1; stroke: orange}}
REFUNDS -- refunds_so_tien_hoan
REFUNDS -- refunds_trang_thai
REFUNDS -- refunds_ly_do
# REFUNDS -- refunds_requested_by: {style: {stroke-width: 1; stroke: orange}}
# REFUNDS -- refunds_approved_by: {style: {stroke-width: 1; stroke: orange}}
# REFUNDS -- refunds_created_at
# REFUNDS -- refunds_updated_at
