# direction: right

# Tiêu đề: căn góc trên-giữa
# title: |md
#   # Mô Hình Thực Thể Quan Hệ (ER Diagram Chen Notation)
# | {near: top-center}

# title.style: {
# font-size: 20
# font: "mono"
# }

# --- 0. STYLES ---
style: {
  # font: "mono"
  opacity: 0.0
  fill: transparent
  # stroke: "orange"
  # stroke-width: 5
}

# --- 1. CSS STYLES (THEME) ---
classes: {
  # Thực thể: Chữ nhật bo góc Apple style
  entity: {
    shape: rectangle
    style: {
      border-radius: 15
      stroke-width: 2
      fill: "#FFFFFF"
      stroke: "#333333"
    }
  }

  # Quan hệ (Relationship): Hình thoi
  rel: {
    shape: diamond
    style: {
      fill: "#F2F2F7"
      stroke: "#8E8E93"
      stroke-width: 2
    }
  }

  # Thuộc tính: Oval
  attr: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
    }
  }

  # Khóa chính: gạch chân
  # viền xanh
  attr_pri: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa chính là khóa khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_pri: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      underline: true
    }
  }

  # Khóa ngoại từ bảng khác
  # gạch chân
  # viền cam
  attr_foreign_key: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#f2840e"
      stroke-width: 1
      # font-size: 20
      # underline: true
    }
  }
}

# MARK: PHONG
PHONG: {class: entity; label: "PHONG"}
phong_id: {class: attr_pri; label: "id"}
phong_so_phong: {class: attr; label: "so_phong"}
phong_loai_phong_id: {class: attr_foreign_key; label: "loai_phong_id"; width: 120}
phong_trang_thai: {class: attr; label: "trang_thai"}

PHONG -- phong_id: {style: {stroke-width: 1}}
PHONG -- phong_so_phong: {style: {stroke-width: 1}}
PHONG -- phong_loai_phong_id: {style: {stroke-width: 1; stroke: orange}}
PHONG -- phong_trang_thai: {style: {stroke-width: 1}}
