direction: right

# --- 0. STYLES ---
style: {
  opacity: 0.0
  fill: transparent
}

# --- 1. SETTINGS ---
classes: {
  entity: {
    shape: rectangle
    style: {border-radius: 10; fill: "#FFFFFF"; stroke: "#333333"}
  }
  rel: {
    shape: diamond
    style: {fill: "#F2F2F7"; stroke: "#8E8E93"}
  }
  attr: {
    shape: oval
    # width: 100; height: 50
    style: {fill: "#F0F8FF"; stroke: "#4682B4"; stroke-dash: 3}
  }
}

# --- 2. ENTITIES ---
ADMINS: {class: entity; label: "Quản Trị Viên"}
DATPHONG: {class: entity; label: "Đặt Phòng"}
DICHVU: {class: entity; label: "Dịch Vụ"}
LOAIPHONG: {class: entity; label: "Loại Phòng"}
PAYMENTS: {class: entity; label: "Thanh Toán"}
PERMISSIONS: {class: entity; label: "Quyền Hạn"}
PHONG: {class: entity; label: "Phòng"}
REFUNDS: {class: entity; label: "Hoàn Tiền"}
REVIEWS: {class: entity; label: "Đánh Giá"}
ROLES: {class: entity; label: "Vai Trò"}
USERS: {class: entity; label: "Người Dùng"}
VOUCHERS: {class: entity; label: "Mã Giảm Giá"}

# --- 3. RELATIONSHIPS ---
# (n, n): được tô sáng để dễ nhận diện

ADMINS -- REFUNDS: một - nhiều
ADMINS -- ROLES: nhiều - nhiều
DATPHONG -- DICHVU: nhiều - nhiều
DATPHONG -- PAYMENTS: một - nhiều
DATPHONG -- PHONG: nhiều - nhiều
DATPHONG -- REVIEWS: một - một
LOAIPHONG -- PHONG: một - nhiều
PAYMENTS -- REFUNDS: một - nhiều
ROLES -- PERMISSIONS: nhiều - nhiều
USERS -- DATPHONG: một - nhiều
USERS -- PAYMENTS: một - nhiều
USERS -- REFUNDS: một - nhiều
USERS -- REVIEWS: một - nhiều
VOUCHERS -- DATPHONG: một - nhiều
